### ISSUE TITLE
Fit light curves using desmos

### ISSUE THREAD

**Issue by fire** [lyuma/Godot-MToon-Shader#1]
// Line of best fit derived from guessing, see https://www.desmos.com/calculator/biiflubp8b
// The points in desmos are not exact, except for (1, infinity).

https://github.com/godotengine/godot/blob/0a1dd5b6e40a628892d8dc95bd05f1dc72d8b4ab/editor/import/editor_scene_importer_gltf.cpp#L2598

**Comment by lyuma** [comment]
I think light curves is outside the scope of this shader. We just follow the attenuation curves given by godot.

Anyway, this repository has moved to https://github.com/V-Sekai/godot-vrm/ so I'm closing all issues here.
